version: '3.9'

services:
  tcpmultiplexer:
    build:
        context: ../Source
        dockerfile: ../Source/TcpMultiplexer.Server/Dockerfile
    hostname: testing.tcpmultiplexer
    command: --listen 0.0.0.0 --port 6000 --autostart
    ports:
      - "5062:6000"
      - "5066:80"

    environment:
      - "ASPNETCORE_ENVIRONMENT=Docker"
      - "DOTNET_URLS=http://+:80;"
      - "ASPNETCORE_URLS=http://+:80;"
      - "DeployVersion=0.0.113"

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - "node.role==manager"

    dns:
      - 10.2.0.1

    dns_search: modelingevolution.local
